extends RefCounted
class_name GameJuiceFlags

const MATCH_POP_CLEAR_BURST := "match_pop_clear_burst"
const GRAVITY_REFILL_OVERSHOOT := "gravity_refill_overshoot"
const COMBO_RHYTHM_PULSE := "combo_rhythm_pulse"
const IMPACT_RINGS_RESULT_LABELS := "impact_rings_result_labels"
const MASTERY_FILL_STREAMS := "mastery_fill_streams"
const MASTERY_CARD_INTAKE_FLARE := "mastery_card_intake_flare"
const SCREEN_NUDGE := "screen_nudge"
const HIT_STOP := "hit_stop"
const ELEMENT_IMPACT_AUDIO := "element_impact_audio"
const ENEMY_REACTION_CHARACTER := "enemy_reaction_character"
const SHOP_CHOICE_FEEDBACK := "shop_choice_feedback"

const ALL_KEYS: Array[String] = [
	MATCH_POP_CLEAR_BURST,
	GRAVITY_REFILL_OVERSHOOT,
	COMBO_RHYTHM_PULSE,
	IMPACT_RINGS_RESULT_LABELS,
	MASTERY_FILL_STREAMS,
	MASTERY_CARD_INTAKE_FLARE,
	SCREEN_NUDGE,
	HIT_STOP,
	ELEMENT_IMPACT_AUDIO,
	ENEMY_REACTION_CHARACTER,
	SHOP_CHOICE_FEEDBACK,
]

const MOTION_HEAVY_KEYS: Array[String] = [
	GRAVITY_REFILL_OVERSHOOT,
	COMBO_RHYTHM_PULSE,
	MASTERY_FILL_STREAMS,
	SCREEN_NUDGE,
	HIT_STOP,
	ENEMY_REACTION_CHARACTER,
	SHOP_CHOICE_FEEDBACK,
]

const LABEL_KEYS := {
	MATCH_POP_CLEAR_BURST: "SETTINGS_JUICE_MATCH_POP_CLEAR_BURST",
	GRAVITY_REFILL_OVERSHOOT: "SETTINGS_JUICE_GRAVITY_REFILL_OVERSHOOT",
	COMBO_RHYTHM_PULSE: "SETTINGS_JUICE_COMBO_RHYTHM_PULSE",
	IMPACT_RINGS_RESULT_LABELS: "SETTINGS_JUICE_IMPACT_RINGS_RESULT_LABELS",
	MASTERY_FILL_STREAMS: "SETTINGS_JUICE_MASTERY_FILL_STREAMS",
	MASTERY_CARD_INTAKE_FLARE: "SETTINGS_JUICE_MASTERY_CARD_INTAKE_FLARE",
	SCREEN_NUDGE: "SETTINGS_JUICE_SCREEN_NUDGE",
	HIT_STOP: "SETTINGS_JUICE_HIT_STOP",
	ELEMENT_IMPACT_AUDIO: "SETTINGS_JUICE_ELEMENT_IMPACT_AUDIO",
	ENEMY_REACTION_CHARACTER: "SETTINGS_JUICE_ENEMY_REACTION_CHARACTER",
	SHOP_CHOICE_FEEDBACK: "SETTINGS_JUICE_SHOP_CHOICE_FEEDBACK",
}

const DESCRIPTION_KEYS := {
	MATCH_POP_CLEAR_BURST: "SETTINGS_JUICE_MATCH_POP_CLEAR_BURST_DESC",
	GRAVITY_REFILL_OVERSHOOT: "SETTINGS_JUICE_GRAVITY_REFILL_OVERSHOOT_DESC",
	COMBO_RHYTHM_PULSE: "SETTINGS_JUICE_COMBO_RHYTHM_PULSE_DESC",
	IMPACT_RINGS_RESULT_LABELS: "SETTINGS_JUICE_IMPACT_RINGS_RESULT_LABELS_DESC",
	MASTERY_FILL_STREAMS: "SETTINGS_JUICE_MASTERY_FILL_STREAMS_DESC",
	MASTERY_CARD_INTAKE_FLARE: "SETTINGS_JUICE_MASTERY_CARD_INTAKE_FLARE_DESC",
	SCREEN_NUDGE: "SETTINGS_JUICE_SCREEN_NUDGE_DESC",
	HIT_STOP: "SETTINGS_JUICE_HIT_STOP_DESC",
	ELEMENT_IMPACT_AUDIO: "SETTINGS_JUICE_ELEMENT_IMPACT_AUDIO_DESC",
	ENEMY_REACTION_CHARACTER: "SETTINGS_JUICE_ENEMY_REACTION_CHARACTER_DESC",
	SHOP_CHOICE_FEEDBACK: "SETTINGS_JUICE_SHOP_CHOICE_FEEDBACK_DESC",
}


static func all_keys() -> Array[String]:
	return ALL_KEYS.duplicate()


static func default_flags() -> Dictionary:
	var defaults := {}
	for key in ALL_KEYS:
		defaults[key] = true
	return defaults


static func normalized_flags(flags: Dictionary = {}) -> Dictionary:
	var normalized := default_flags()
	for key in ALL_KEYS:
		if flags.has(key):
			normalized[key] = bool(flags.get(key, true))
	return normalized


static func is_valid_key(key: String) -> bool:
	return ALL_KEYS.has(key)


static func is_motion_heavy(key: String) -> bool:
	return MOTION_HEAVY_KEYS.has(key)


static func label_key(key: String) -> String:
	return String(LABEL_KEYS.get(key, key))


static func description_key(key: String) -> String:
	return String(DESCRIPTION_KEYS.get(key, key))
