extends RefCounted
class_name ContentRegistryDefaultEquipment


func build(entry_factory: RefCounted) -> Array[Dictionary]:
	return [
		entry_factory.make_equipment(
			"shortsword",
			"Iron Shortsword",
			"common",
			"white",
			"shortsword",
			OrbType.Id.FIRE,
			10,
			"Deal +2 flat elemental damage each turn.",
			"equipment_shortsword",
			{"flat_damage_bonus": 2},
			"shortsword_knight",
			0
		),
		entry_factory.make_equipment(
			"buckler",
			"Wooden Buckler",
			"common",
			"white",
			"buckler",
			OrbType.Id.ARMOR,
			11,
			"Gain +2 armor at turn start.",
			"equipment_buckler",
			{"start_turn_armor": 2},
			"buckler_iron",
			0
		),
		entry_factory.make_equipment(
			"coin_purse",
			"Worn Coin Purse",
			"common",
			"white",
			"coin_purse",
			OrbType.Id.GOLD,
			10,
			"Gain +1 bonus gold when gold orbs resolve.",
			"equipment_coin_purse",
			{"flat_gold_bonus": 1},
			"coin_purse_merchant",
			0
		),
		entry_factory.make_equipment(
			"healing_charm",
			"Linen Healing Charm",
			"common",
			"white",
			"healing_charm",
			OrbType.Id.HEART,
			11,
			"Gain +2 bonus healing when heart orbs resolve.",
			"equipment_healing_charm",
			{"flat_heal_bonus": 2},
			"healing_charm_blessed",
			0
		),
		entry_factory.make_equipment(
			"leather_gloves",
			"Leather Gloves",
			"common",
			"white",
			"leather_gloves",
			-1,
			11,
			"Combo count is treated as +1 for damage scaling.",
			"equipment_leather_gloves",
			{"combo_flat_bonus": 1},
			"leather_gloves_duelist",
			0
		),
		entry_factory.make_equipment(
			"shortsword_knight",
			"Knight Shortsword",
			"uncommon",
			"blue",
			"shortsword",
			OrbType.Id.FIRE,
			18,
			"Deal +4 flat elemental damage each turn.",
			"equipment_shortsword_knight",
			{"flat_damage_bonus": 4},
			"shortsword_royal",
			100,
			2
		),
		entry_factory.make_equipment(
			"buckler_iron",
			"Iron Buckler",
			"uncommon",
			"blue",
			"buckler",
			OrbType.Id.ARMOR,
			19,
			"Gain +4 armor at turn start.",
			"equipment_buckler_iron",
			{"start_turn_armor": 4},
			"buckler_guardian",
			100,
			2
		),
		entry_factory.make_equipment(
			"coin_purse_merchant",
			"Merchant Coin Purse",
			"uncommon",
			"blue",
			"coin_purse",
			OrbType.Id.GOLD,
			17,
			"Gain +2 bonus gold when gold orbs resolve.",
			"equipment_coin_purse_merchant",
			{"flat_gold_bonus": 2},
			"coin_purse_noble",
			100,
			2
		),
		entry_factory.make_equipment(
			"healing_charm_blessed",
			"Blessed Healing Charm",
			"uncommon",
			"blue",
			"healing_charm",
			OrbType.Id.HEART,
			17,
			"Gain +4 bonus healing when heart orbs resolve.",
			"equipment_healing_charm_blessed",
			{"flat_heal_bonus": 4},
			"healing_charm_saint",
			100,
			2
		),
		entry_factory.make_equipment(
			"leather_gloves_duelist",
			"Duelist Gloves",
			"uncommon",
			"blue",
			"leather_gloves",
			-1,
			18,
			"Combo count is treated as +2 for damage scaling.",
			"equipment_leather_gloves_duelist",
			{"combo_flat_bonus": 2},
			"leather_gloves_blademaster",
			100,
			2
		),
		entry_factory.make_equipment(
			"shortsword_royal",
			"Royal Shortsword",
			"rare",
			"purple",
			"shortsword",
			OrbType.Id.FIRE,
			27,
			"Deal +6 flat elemental damage each turn.",
			"equipment_shortsword_royal",
			{"flat_damage_bonus": 6},
			"",
			300,
			3
		),
		entry_factory.make_equipment(
			"buckler_guardian",
			"Guardian Buckler",
			"rare",
			"purple",
			"buckler",
			OrbType.Id.ARMOR,
			29,
			"Gain +6 armor at turn start.",
			"equipment_buckler_guardian",
			{"start_turn_armor": 6},
			"",
			300,
			3
		),
		entry_factory.make_equipment(
			"coin_purse_noble",
			"Noble Coin Purse",
			"rare",
			"purple",
			"coin_purse",
			OrbType.Id.GOLD,
			27,
			"Gain +3 bonus gold when gold orbs resolve.",
			"equipment_coin_purse_noble",
			{"flat_gold_bonus": 3},
			"",
			300,
			3
		),
		entry_factory.make_equipment(
			"healing_charm_saint",
			"Saint's Healing Charm",
			"rare",
			"purple",
			"healing_charm",
			OrbType.Id.HEART,
			27,
			"Gain +6 bonus healing when heart orbs resolve.",
			"equipment_healing_charm_saint",
			{"flat_heal_bonus": 6},
			"",
			300,
			3
		),
		entry_factory.make_equipment(
			"leather_gloves_blademaster",
			"Blademaster Gloves",
			"rare",
			"purple",
			"leather_gloves",
			-1,
			28,
			"Combo count is treated as +3 for damage scaling.",
			"equipment_leather_gloves_blademaster",
			{"combo_flat_bonus": 3},
			"",
			300,
			3
		),
	]
